"""
Per-document rule storage (Phase 4A of parsing-architecture refactor).

Holds regex/normalization rules attached to a *specific*
``document_identity`` row — never to a parser profile. Phase 4B's
rule-attachment generator writes here; Phase 4C's promotion path reads
from here. Phase 5C eventually rewires the overnight loop to consume
from this table for Tier 3 docs.

This module ships only the schema, dataclass, and CRUD helpers. The
generator (4B) and promotion path (4C) live in their own modules so
each piece is independently testable.

Plan reference: ``docs/PARSING_ARCHITECTURE_REFACTOR_PLAN.md`` §7.4A.

Why per-document scoping?
    The greedy-regex problem in the legacy pipeline came from rules
    being attached to "the profile." A rule that worked on one doc
    would auto-apply to every other doc in that profile and false-
    positive. Per-doc rules carry their own identity, so they can't
    leak.

Status lifecycle (matches plan §7.4):
    pending      → created by 4B, not yet validated
    accepted     → passed 4B's narrow validation (target doc + siblings)
    rejected     → produced out-of-range values or zero matches
    promoted     → 4C lifted it to a template-level rule
    superseded   → replaced by a stricter or broader rule
    retired      → manually removed from circulation
"""

from __future__ import annotations

import json
import logging
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


ALLOWED_STATUSES: tuple[str, ...] = (
    "pending",       # created, not yet validated
    "accepted",      # passed narrow validation against target + siblings
    "rejected",      # validation said no
    "promoted",      # 4C lifted to template-level
    "superseded",    # newer rule replaces this one
    "retired",       # manually removed
)


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

_DDL_DOCUMENT_SPECIFIC_RULES = """
CREATE TABLE IF NOT EXISTS document_specific_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_identity_id INTEGER NOT NULL REFERENCES document_identity(id),
    candidate_regex TEXT NOT NULL,
    candidate_normalization TEXT,
    expected_unit TEXT,
    target_field TEXT,
    -- Back-link to llm_regex_suggestions when this rule was generated by
    -- the suggest pipeline (so we don't lose the original prompt context).
    suggestion_id INTEGER,
    status TEXT NOT NULL DEFAULT 'pending',
    -- Plan §7.4C — incremented when a sibling doc's rule shares a
    -- string-similar regex; promotion threshold is 3+ siblings.
    promotion_eligible_count INTEGER NOT NULL DEFAULT 0,
    -- The rule that superseded this one, if any.
    superseded_by INTEGER,
    notes TEXT NOT NULL DEFAULT '',
    last_updated TEXT NOT NULL DEFAULT (datetime('now')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
"""

_DDL_INDEX_DOC = (
    "CREATE INDEX IF NOT EXISTS idx_doc_specific_rules_doc "
    "ON document_specific_rules(document_identity_id);"
)
_DDL_INDEX_STATUS = (
    "CREATE INDEX IF NOT EXISTS idx_doc_specific_rules_status "
    "ON document_specific_rules(status);"
)
_DDL_INDEX_SUGGESTION = (
    "CREATE INDEX IF NOT EXISTS idx_doc_specific_rules_suggestion "
    "ON document_specific_rules(suggestion_id);"
)


def ensure_schema(db_path: Path | str) -> None:
    """Idempotent schema bootstrap.

    Phase 4B's generator and Phase 4C's promotion path both call this
    before reading or writing the table.
    """
    try:
        conn = sqlite3.connect(str(db_path))
        conn.execute(_DDL_DOCUMENT_SPECIFIC_RULES)
        conn.execute(_DDL_INDEX_DOC)
        conn.execute(_DDL_INDEX_STATUS)
        conn.execute(_DDL_INDEX_SUGGESTION)
        conn.commit()
        conn.close()
    except Exception:
        logger.warning(
            "document_specific_rules schema bootstrap failed", exc_info=True,
        )


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class DocumentSpecificRule:
    """Typed view of one ``document_specific_rules`` row.

    The ``id`` is None until the row is persisted (insert returns the
    rowid). Defaults match the SQL DDL.
    """

    document_identity_id: int
    candidate_regex: str
    candidate_normalization: str | None = None
    expected_unit: str | None = None
    target_field: str | None = None
    suggestion_id: int | None = None
    status: str = "pending"
    promotion_eligible_count: int = 0
    superseded_by: int | None = None
    notes: str = ""
    id: int | None = None
    last_updated: str | None = None
    created_at: str | None = None

    def to_insert_tuple(self) -> tuple[Any, ...]:
        return (
            self.document_identity_id,
            self.candidate_regex,
            self.candidate_normalization,
            self.expected_unit,
            self.target_field,
            self.suggestion_id,
            self.status,
            self.promotion_eligible_count,
            self.superseded_by,
            self.notes,
        )


# ---------------------------------------------------------------------------
# CRUD helpers
# ---------------------------------------------------------------------------


def insert_rule(db_path: Path | str, rule: DocumentSpecificRule) -> int:
    """Insert one rule; returns the new row's id.

    Validates ``status`` against ALLOWED_STATUSES; raises ValueError on
    bad input rather than silently writing junk.
    """
    if rule.status not in ALLOWED_STATUSES:
        raise ValueError(
            f"invalid status {rule.status!r}; allowed: {ALLOWED_STATUSES}"
        )
    ensure_schema(db_path)
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            """
            INSERT INTO document_specific_rules
                (document_identity_id, candidate_regex,
                 candidate_normalization, expected_unit, target_field,
                 suggestion_id, status, promotion_eligible_count,
                 superseded_by, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            rule.to_insert_tuple(),
        )
        rule_id = cur.lastrowid
        conn.commit()
        return int(rule_id) if rule_id is not None else 0
    finally:
        conn.close()


def update_status(
    db_path: Path | str,
    rule_id: int,
    status: str,
    *,
    notes: str | None = None,
    superseded_by: int | None = None,
) -> bool:
    """Update a rule's status (and optionally its notes / supersession).

    Returns True if a row was updated.
    """
    if status not in ALLOWED_STATUSES:
        raise ValueError(
            f"invalid status {status!r}; allowed: {ALLOWED_STATUSES}"
        )
    sets = ["status = ?", "last_updated = datetime('now')"]
    params: list[Any] = [status]
    if notes is not None:
        sets.append("notes = ?")
        params.append(notes)
    if superseded_by is not None:
        sets.append("superseded_by = ?")
        params.append(superseded_by)
    params.append(rule_id)
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            f"UPDATE document_specific_rules SET {', '.join(sets)} WHERE id = ?",
            params,
        )
        conn.commit()
        return cur.rowcount > 0
    finally:
        conn.close()


def fetch_rule(db_path: Path | str, rule_id: int) -> DocumentSpecificRule | None:
    """Fetch one rule by id."""
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        row = conn.execute(
            "SELECT * FROM document_specific_rules WHERE id = ? LIMIT 1",
            (rule_id,),
        ).fetchone()
        return _row_to_rule(row) if row else None
    finally:
        conn.close()


def fetch_rules_for_document(
    db_path: Path | str, document_identity_id: int, *, status: str | None = None
) -> list[DocumentSpecificRule]:
    """All rules attached to a specific document_identity id.

    Useful for Phase 5C when the routing layer needs to know "what
    per-doc rules apply to this PDF."
    """
    sql = "SELECT * FROM document_specific_rules WHERE document_identity_id = ?"
    params: list[Any] = [document_identity_id]
    if status is not None:
        if status not in ALLOWED_STATUSES:
            raise ValueError(
                f"invalid status {status!r}; allowed: {ALLOWED_STATUSES}"
            )
        sql += " AND status = ?"
        params.append(status)
    sql += " ORDER BY id DESC"
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        rows = conn.execute(sql, params).fetchall()
        return [_row_to_rule(r) for r in rows]
    finally:
        conn.close()


def increment_promotion_count(
    db_path: Path | str, rule_id: int, delta: int = 1
) -> int:
    """Bump ``promotion_eligible_count`` and return the new value.

    Phase 4C uses this when it observes a sibling doc with a string-
    similar rule.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute(
            """
            UPDATE document_specific_rules
            SET promotion_eligible_count = promotion_eligible_count + ?,
                last_updated = datetime('now')
            WHERE id = ?
            """,
            (int(delta), rule_id),
        )
        conn.commit()
        cur = conn.execute(
            "SELECT promotion_eligible_count FROM document_specific_rules WHERE id = ?",
            (rule_id,),
        )
        row = cur.fetchone()
        return int(row[0]) if row else 0
    finally:
        conn.close()


def fetch_status_summary(db_path: Path | str) -> dict[str, Any]:
    """Aggregate counts for the dashboard.

    Returns a dict with:
      - total
      - by_status: status -> count
      - promotion_candidates: count of rows where promotion_eligible_count >= 3
        and status = 'accepted'
      - sample_pending: up to 10 most-recent pending rows for spot inspection
    """
    ensure_schema(db_path)
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        total = conn.execute(
            "SELECT COUNT(*) FROM document_specific_rules"
        ).fetchone()[0]
        status_rows = conn.execute(
            "SELECT status, COUNT(*) FROM document_specific_rules GROUP BY status"
        ).fetchall()
        promo_count = conn.execute(
            """
            SELECT COUNT(*) FROM document_specific_rules
            WHERE status = 'accepted'
              AND promotion_eligible_count >= 3
            """
        ).fetchone()[0]
        sample_rows = conn.execute(
            """
            SELECT id, document_identity_id, status, target_field,
                   substr(candidate_regex, 1, 60) AS regex_preview,
                   promotion_eligible_count, created_at
            FROM document_specific_rules
            WHERE status = 'pending'
            ORDER BY id DESC LIMIT 10
            """
        ).fetchall()
    finally:
        conn.close()
    return {
        "total": int(total),
        "by_status": {r["status"]: int(r[1]) for r in status_rows},
        "promotion_candidates": int(promo_count),
        "sample_pending": [dict(r) for r in sample_rows],
    }


# ---------------------------------------------------------------------------
# Internal — row mapping
# ---------------------------------------------------------------------------


def _row_to_rule(row: sqlite3.Row) -> DocumentSpecificRule:
    return DocumentSpecificRule(
        id=row["id"],
        document_identity_id=row["document_identity_id"],
        candidate_regex=row["candidate_regex"] or "",
        candidate_normalization=row["candidate_normalization"],
        expected_unit=row["expected_unit"],
        target_field=row["target_field"],
        suggestion_id=row["suggestion_id"],
        status=row["status"],
        promotion_eligible_count=int(row["promotion_eligible_count"] or 0),
        superseded_by=row["superseded_by"],
        notes=row["notes"] or "",
        last_updated=row["last_updated"],
        created_at=row["created_at"],
    )
